export const ages = [
	'Childhood',
	'Adolescence',
	'Young Adulthood',
	'Adulthood',
	'Middle-Age',
	'Old Age',
	'Ancient'
];

export const flaws = [
	'Fearful',
	'Paranoia',
	'Megalomaniac',
	'Addictive Personality',
	'Foolish',
	'Impulsive',
	'Impish',
	'Socially Awkward',
	'Oblivious',
	'Cold-hearted',
	'Thief',
	'Control Freak',
	'Hedonist',
	'Technophile',
	'Liar',
	'Cynic',
	'Reckless',
	'Solipsist',
	'Wrathful',
	'Fatalistic',
	'Vain',
	'Nihilist'
];

export const ideals = [
	'Individualism',
	'Generosity',
	'Anti-establishment',
	'Anti-technology',
	'Pragmatism',
	'Pleasure',
	'Technological Adaptation',
	'Honor',
	'Information Freedom',
	'Salvation',
	'Empathy for the Marginalized',
	'Power',
	'Survival and Adaptability',
	'The Ends',
	'Transmortalism',
	'Order',
	'Justice',
	'Heroism',
	'Compassion'
];

export const vibes = [
	'Long shadow',
	'Sleepy mood',
	'Street-smart',
	'Outcast mannerisms',
	'Permanent grimace',
	'Corporate air',
	'Bursting energy',
	'Mysterious aspect',
	'Gentle disposition',
	'Androgynous mien',
	'Thousand-yard stare',
	'High-strung',
	'Brooding presence',
	'Friendly demeanor',
	'Meandering gaze',
	'Graceful carriage',
	'Captivating grin',
	'Raucous laugh',
	'Flawless poise',
	'Fiery temper',
	'Menacing aura'
];
